import './js/mxClient';
import './js/util/mxLog';
import './js/util/mxObjectIdentity';
import './js/util/mxDictionary';
import './js/util/mxResources';
import './js/util/mxPoint';
import './js/util/mxRectangle';
import './js/util/mxEffects';
import './js/util/mxUtils';
import './js/util/mxConstants';
import './js/util/mxEventObject';
import './js/util/mxMouseEvent';
import './js/util/mxEventSource';
import './js/util/mxEvent';
import './js/util/mxXmlRequest';
import './js/util/mxClipboard';
import './js/util/mxWindow';
import './js/util/mxForm';
import './js/util/mxImage';
import './js/util/mxDivResizer';
import './js/util/mxDragSource';
import './js/util/mxToolbar';
import './js/util/mxUndoableEdit';
import './js/util/mxUndoManager';
import './js/util/mxUrlConverter';
import './js/util/mxPanningManager';
import './js/util/mxPopupMenu';
import './js/util/mxAutoSaveManager';
import './js/util/mxAnimation';
import './js/util/mxMorphing';
import './js/util/mxImageBundle';
import './js/util/mxImageExport';
import './js/util/mxAbstractCanvas2D';
import './js/util/mxXmlCanvas2D';
import './js/util/mxSvgCanvas2D';
import './js/util/mxVmlCanvas2D';
import './js/util/mxGuide';
import './js/shape/mxStencil';
import './js/shape/mxShape';
import './js/shape/mxStencilRegistry';
import './js/shape/mxMarker';
import './js/shape/mxActor';
import './js/shape/mxCloud';
import './js/shape/mxRectangleShape';
import './js/shape/mxEllipse';
import './js/shape/mxDoubleEllipse';
import './js/shape/mxRhombus';
import './js/shape/mxPolyline';
import './js/shape/mxArrow';
import './js/shape/mxArrowConnector';
import './js/shape/mxText';
import './js/shape/mxTriangle';
import './js/shape/mxHexagon';
import './js/shape/mxLine';
import './js/shape/mxImageShape';
import './js/shape/mxLabel';
import './js/shape/mxCylinder';
import './js/shape/mxConnector';
import './js/shape/mxSwimlane';
// import './js/layout/mxGraphLayout';
// import './js/layout/mxStackLayout';
// import './js/layout/mxPartitionLayout';
// import './js/layout/mxCompactTreeLayout';
// import './js/layout/mxRadialTreeLayout';
// import './js/layout/mxFastOrganicLayout';
// import './js/layout/mxCircleLayout';
// import './js/layout/mxParallelEdgeLayout';
// import './js/layout/mxCompositeLayout';
// import './js/layout/mxEdgeLabelLayout';
// import './js/layout/hierarchical/model/mxGraphAbstractHierarchyCell';
// import './js/layout/hierarchical/model/mxGraphHierarchyNode';
// import './js/layout/hierarchical/model/mxGraphHierarchyEdge';
// import './js/layout/hierarchical/model/mxGraphHierarchyModel';
// import './js/layout/hierarchical/model/mxSwimlaneModel';
// import './js/layout/hierarchical/stage/mxHierarchicalLayoutStage';
// import './js/layout/hierarchical/stage/mxMedianHybridCrossingReduction';
// import './js/layout/hierarchical/stage/mxMinimumCycleRemover';
// import './js/layout/hierarchical/stage/mxCoordinateAssignment';
// import './js/layout/hierarchical/stage/mxSwimlaneOrdering';
// import './js/layout/hierarchical/mxHierarchicalLayout';
// import './js/layout/hierarchical/mxSwimlaneLayout';
import './js/model/mxGraphModel';
import './js/model/mxCell';
import './js/model/mxGeometry';
import './js/model/mxCellPath';
import './js/view/mxPerimeter';
import './js/view/mxPrintPreview';
import './js/view/mxStylesheet';
import './js/view/mxCellState';
import './js/view/mxGraphSelectionModel';
import './js/view/mxCellEditor';
import './js/view/mxCellRenderer';
import './js/view/mxEdgeStyle';
import './js/view/mxStyleRegistry';
import './js/view/mxGraphView';
import './js/view/mxGraph';
import './js/view/mxCellOverlay';
import './js/view/mxOutline';
import './js/view/mxMultiplicity';
import './js/view/mxLayoutManager';
import './js/view/mxSwimlaneManager';
import './js/view/mxTemporaryCellStates';
import './js/view/mxCellStatePreview';
import './js/view/mxConnectionConstraint';
import './js/handler/mxGraphHandler';
import './js/handler/mxPanningHandler';
import './js/handler/mxPopupMenuHandler';
import './js/handler/mxCellMarker';
import './js/handler/mxSelectionCellsHandler';
import './js/handler/mxConnectionHandler';
import './js/handler/mxConstraintHandler';
import './js/handler/mxRubberband';
import './js/handler/mxHandle';
import './js/handler/mxVertexHandler';
import './js/handler/mxEdgeHandler';
import './js/handler/mxElbowEdgeHandler';
import './js/handler/mxEdgeSegmentHandler';
import './js/handler/mxKeyHandler';
import './js/handler/mxTooltipHandler';
import './js/handler/mxCellTracker';
import './js/handler/mxCellHighlight';
import './js/editor/mxDefaultKeyHandler';
import './js/editor/mxDefaultPopupMenu';
import './js/editor/mxDefaultToolbar';
import './js/editor/mxEditor';
import './js/io/mxCodecRegistry';
import './js/io/mxCodec';
import './js/io/mxObjectCodec';
import './js/io/mxCellCodec';
import './js/io/mxModelCodec';
import './js/io/mxRootChangeCodec';
import './js/io/mxChildChangeCodec';
import './js/io/mxTerminalChangeCodec';
import './js/io/mxGenericChangeCodec';
import './js/io/mxGraphCodec';
import './js/io/mxGraphViewCodec';
import './js/io/mxStylesheetCodec';
import './js/io/mxDefaultKeyHandlerCodec';
import './js/io/mxDefaultToolbarCodec';
import './js/io/mxDefaultPopupMenuCodec';
import './js/io/mxEditorCodec';

import './css/common.css';
